const TabContentData = [
  {
    id: 1,
    bankName: "VietinBank",
    amount: "80,000,000đ",
    info: ["9%", "Ưu đãi thông thường", "8 ngày làm việc"],
    desc: "Quỹ để củng cố tài sản lưu thông",
    category: "business",
  },
  {
    id: 2,
    bankName: "SaigonBank",
    amount: "50,000,000đ",
    info: ["10%", "Ưu đãi thông thường", "7 ngày làm việc"],
    desc: "Một bàn tay giúp đỡ cho một công ty nhỏ trả lương cho nhân viên.",
    category: "business",
  },
  {
    id: 3,
    bankName: "VietcomBank",
    amount: "100,000,000đ",
    info: ["10%", "Ưu đãi hấp dẫn", "9 ngày làm việc"],
    desc: "Ưu đãi thuận lợi từ một trong những ngân hàng lớn nhất",
    category: "business",
  },
  {
    id: 4,
    bankName: "MbBank",
    amount: "40,000,000đ",
    info: ["12%", "Ưu đãi trực tuyến", "5 ngày làm việc"],
    desc: "Ưu đãi chỉ trực tuyến cho các doanh nghiệp nhỏ, chỉ trong 2 tuần.",
    category: "business",
  },
  {
    id: 5,
    bankName: "MbBank",
    amount: "10,000,000đ",
    info: ["10%", "Ưu đãi trực tuyến", "5 ngày làm việc"],
    desc: "Gói vay hợp lý dành cho sinh viên đóng học phí.",
    category: "student",
  },
  {
    id: 6,
    bankName: "VpBank",
    amount: "4,000,000đ",
    info: ["7%", "Ưu đãi hấp dẫn", "2 ngày làm việc"],
    desc: "Giải pháp cứu cánh cho sinh viên cuối tháng.",
    category: "student",
  },
  {
    id: 7,
    bankName: "AgriBank",
    amount: "25,000,000đ",
    info: ["9%", "Ưu đãi tại quầy", "3 ngày làm việc"],
    desc: "Khoản quỹ dành cho sinh viên khởi nghiệp.",
    category: "student",
  },
  {
    id: 8,
    bankName: "Vib",
    amount: "50,000,000",
    info: ["11%", "Ưu đãi tại quầy", "7 ngày làm việc"],
    desc: "Số tiền hồi môn cho sinh viên kết hôn",
    category: "student",
  },
  {
    id: 9,
    bankName: "Vib",
    amount: "3,000,000đ",
    info: ["12%", "Ưu đãi thông thường", "2 ngày làm việc"],
    desc: "Khoản tiền hữu ích cho người già có nhu cầu",
    category: "elderly",
  },
  {
    id: 10,
    bankName: "SacomBank",
    amount: "40,000,000đ",
    info: ["11%", "Ưu đãi tại quầy", "6 ngày làm việc"],
    desc: "Giải pháp toàn diện cho việc sửa nhà dưỡng già",
    category: "elderly",
  },
  {
    id: 11,
    bankName: "ACB",
    amount: "15,000,000đ",
    info: ["0%", "Ưu đãi nhân từ", "6 ngày làm việc"],
    desc: "Dành cho người già hoàn cảnh nhưng phải lo cho gia đình",
    category: "elderly",
  },
  {
    id: 12,
    bankName: "TechcomBank",
    amount: "100,000,000đ",
    info: ["14%", "Ưu đãi tại quầy", "6 ngày làm việc"],
    desc: "Quỹ dành cho doanh nghiệp vận hành vốn",
    category: "elderly",
  },
];

export default TabContentData;
